FEATURE_COLUMNS = [
    'LOC_X',
    'LOC_Y',
    'SHOT_DISTANCE',
    'PERIOD',
    'TOTAL_SECONDS_REMAINING',
]

ZONE_COLUMNS = ['SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE']

CATEGORICAL_COLUMNS = ['SHOT_TYPE', 'ACTION_TYPE']

TARGET_COLUMN = 'SHOT_MADE_FLAG'